export const OBTENER_EMPLEADOS_PENDIENTE = 'OBTENER_EMPLEADOS_PENDIENTE'
export const OBTENER_EMPLEADOS_RECHAZADO = 'OBTENER_EMPLEADOS_RECHAZADO'
export const OBTENER_EMPLEADOS_COMPLETADO = 'OBTENER_EMPLEADOS_COMPLETADO'
//------------------------------------------------------------------------
export const ELIMINAR_EMPLEADO_PENDIENTE = 'ELIMINAR_EMPLEADO_PENDIENTE'
export const ELIMINAR_EMPLEADO_RECHAZADO = 'ELIMINAR_EMPLEADO_RECHAZADO'
export const ELIMINAR_EMPLEADO_COMPLETADO = 'ELIMINAR_EMPLEADO_COMPLETADO'
//------------------------------------------------------------------------
export const AGREGAR_EMPLEADO_PENDIENTE = 'AGREGAR_EMPLEADO_PENDIENTE'
export const AGREGAR_EMPLEADO_RECHAZADO = 'AGREGAR_EMPLEADO_RECHAZADO'
export const AGREGAR_EMPLEADO_COMPLETADO = 'AGREGAR_EMPLEADO_COMPLETADO'
//----------------------------------------------------------------------
export const OBTENER_EMPLEADO_EDITAR = 'OBTENER_EMPLEADO_EDITAR'
export const EDITAR_EMPLEADO_PENDIENTE = 'EDITAR_EMPLEADO_PENDIENTE'
export const EDITAR_EMPLEADO_RECHAZADO = 'EDITAR_EMPLEADO_RECHAZADO'
export const EDITAR_EMPLEADO_COMPLETADO = 'EDITAR_EMPLEADO_COMPLETADO'
//--------------------------------------------------------------------